-- Baseline migration: describes the schema as it already exists on the live
-- database (built up over time via `drizzle-kit push`, before this repo
-- switched to versioned migrations — see #15). Every statement is written to
-- be a no-op when the object already exists, so this migration is safe to
-- "apply" against the live DB on the first migrate run without erroring or
-- touching anything. Do not edit this file to add new schema changes — add a
-- new migration instead (`npm run db:generate`).
CREATE TABLE IF NOT EXISTS "guests" (
	"id" serial PRIMARY KEY NOT NULL,
	"party_id" integer NOT NULL,
	"name" text NOT NULL,
	"name_key" text NOT NULL,
	"phone" text,
	"arrival_flight" text,
	"arrival_time" text,
	"departure_flight" text,
	"departure_time" text,
	"dietary" text,
	"activity_prefs" jsonb,
	"notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "parties" (
	"id" serial PRIMARY KEY NOT NULL,
	"slug" text NOT NULL,
	"password" text NOT NULL,
	"admin_token" text,
	"content" jsonb NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "parties_slug_unique" UNIQUE("slug"),
	CONSTRAINT "parties_password_unique" UNIQUE("password")
);
--> statement-breakpoint
DO $$ BEGIN
	ALTER TABLE "guests" ADD CONSTRAINT "guests_party_id_parties_id_fk" FOREIGN KEY ("party_id") REFERENCES "public"."parties"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
	WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "guests_party_name_idx" ON "guests" USING btree ("party_id","name_key");
